gText_Norman1:: @ 82C897B
	.string "Hijo… ¿Estás dormido?\p"
	.string "$"

gText_Norman2::
	.string "Ha sido un duro día de mudanzas,\n"
	.string "¿verdad?\p"
	.string "$"

gText_Norman3::
	.string " Estaba imaginándome como será nuestra\n batalla…\p"
	.string "$"

gText_Norman3b::
	.string " Nada me hace más ilusión que poder\n"
	.string " enfrentarme a tí, hijo.\p"
	.string "$"

gText_Norman3c::
	.string " Ser líder de gimnasio…\p"
	.string "$"

gText_Norman3d::
	.string " He luchado mucho por ello.\p"
	.string "$"

gText_Norman4::
	.string "Bueno, no quiero molestarte más.\p"
	.string	"Detrás tienes unas cajas con tus\n"
	.string "pertenencias.\p"
	.string "Ponle tu nombre para no confundirme\n"
	.string "cuando lleguemos.\p"
	.string "$"

